CONFRONTOS_LIGA = [
    {
        "rodada_brasileirao": 1,
        "rodada_liga": 1,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 1,
        "rodada_liga": 1,
        "time1": "Arãcanela F.C.",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 1,
        "rodada_liga": 1,
        "time1": "Ansiedade Prime FC",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 1,
        "rodada_liga": 1,
        "time1": "Baguetty e os perus",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 1,
        "rodada_liga": 1,
        "time1": "Kyrolina FC",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 1,
        "rodada_liga": 1,
        "time1": "Club silencio",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 2,
        "rodada_liga": 2,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 2,
        "rodada_liga": 2,
        "time1": "Ansiedade Prime FC",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 2,
        "rodada_liga": 2,
        "time1": "Baguetty e os perus",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 2,
        "rodada_liga": 2,
        "time1": "Kyrolina FC",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 2,
        "rodada_liga": 2,
        "time1": "Club silencio",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 2,
        "rodada_liga": 2,
        "time1": "GARANTES",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 3,
        "rodada_liga": 3,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 3,
        "rodada_liga": 3,
        "time1": "Baguetty e os perus",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 3,
        "rodada_liga": 3,
        "time1": "Kyrolina FC",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 3,
        "rodada_liga": 3,
        "time1": "Club silencio",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 3,
        "rodada_liga": 3,
        "time1": "GARANTES",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 3,
        "rodada_liga": 3,
        "time1": "Travesseiros confortáveis FC",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 4,
        "rodada_liga": 4,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 4,
        "rodada_liga": 4,
        "time1": "Kyrolina FC",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 4,
        "rodada_liga": 4,
        "time1": "Club silencio",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 4,
        "rodada_liga": 4,
        "time1": "GARANTES",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 4,
        "rodada_liga": 4,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 4,
        "rodada_liga": 4,
        "time1": "São Janumário FC",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 5,
        "rodada_liga": 5,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 5,
        "rodada_liga": 5,
        "time1": "Club silencio",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 5,
        "rodada_liga": 5,
        "time1": "GARANTES",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 5,
        "rodada_liga": 5,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 5,
        "rodada_liga": 5,
        "time1": "São Janumário FC",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 5,
        "rodada_liga": 5,
        "time1": "Paquetetra",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 6,
        "rodada_liga": 6,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 6,
        "rodada_liga": 6,
        "time1": "GARANTES",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 6,
        "rodada_liga": 6,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 6,
        "rodada_liga": 6,
        "time1": "São Janumário FC",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 6,
        "rodada_liga": 6,
        "time1": "Paquetetra",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 6,
        "rodada_liga": 6,
        "time1": "Inhames",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 7,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 7,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 7,
        "time1": "São Janumário FC",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 7,
        "time1": "Paquetetra",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 7,
        "time1": "Inhames",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 7,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 8,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 8,
        "time1": "São Janumário FC",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 8,
        "time1": "Paquetetra",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 8,
        "time1": "Inhames",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 8,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 8,
        "time1": "Arãcanela F.C.",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 9,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 9,
        "time1": "Paquetetra",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 9,
        "time1": "Inhames",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 9,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 9,
        "time1": "Arãcanela F.C.",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 9,
        "time1": "Ansiedade Prime FC",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 10,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 10,
        "time1": "Inhames",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 10,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 10,
        "time1": "Arãcanela F.C.",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 10,
        "time1": "Ansiedade Prime FC",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 10,
        "time1": "Baguetty e os perus",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 11,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 11,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 11,
        "time1": "Arãcanela F.C.",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 11,
        "time1": "Ansiedade Prime FC",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 11,
        "time1": "Baguetty e os perus",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 11,
        "time1": "Kyrolina FC",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 12,
        "time1": "Pigeon Boiteux OSC",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 12,
        "time1": "Inhames",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 12,
        "time1": "Paquetetra",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 12,
        "time1": "São Janumário FC",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 12,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 12,
        "time1": "GARANTES",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 10,
        "rodada_liga": 13,
        "time1": "Arãcanela F.C.",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 10,
        "rodada_liga": 13,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 10,
        "rodada_liga": 13,
        "time1": "Inhames",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 10,
        "rodada_liga": 13,
        "time1": "Paquetetra",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 10,
        "rodada_liga": 13,
        "time1": "São Janumário FC",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 10,
        "rodada_liga": 13,
        "time1": "Travesseiros confortáveis FC",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 11,
        "rodada_liga": 14,
        "time1": "Ansiedade Prime FC",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 11,
        "rodada_liga": 14,
        "time1": "Arãcanela F.C.",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 11,
        "rodada_liga": 14,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 11,
        "rodada_liga": 14,
        "time1": "Inhames",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 11,
        "rodada_liga": 14,
        "time1": "Paquetetra",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 11,
        "rodada_liga": 14,
        "time1": "São Janumário FC",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 12,
        "rodada_liga": 15,
        "time1": "Baguetty e os perus",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 12,
        "rodada_liga": 15,
        "time1": "Ansiedade Prime FC",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 12,
        "rodada_liga": 15,
        "time1": "Arãcanela F.C.",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 12,
        "rodada_liga": 15,
        "time1": "Pigeon Boiteux OSC",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 12,
        "rodada_liga": 15,
        "time1": "Inhames",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 12,
        "rodada_liga": 15,
        "time1": "Paquetetra",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 13,
        "rodada_liga": 16,
        "time1": "Kyrolina FC",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 13,
        "rodada_liga": 16,
        "time1": "Baguetty e os perus",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 13,
        "rodada_liga": 16,
        "time1": "Ansiedade Prime FC",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 13,
        "rodada_liga": 16,
        "time1": "Arãcanela F.C.",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 13,
        "rodada_liga": 16,
        "time1": "Pigeon Boiteux OSC",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 13,
        "rodada_liga": 16,
        "time1": "Inhames",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 14,
        "rodada_liga": 17,
        "time1": "Club silencio",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 14,
        "rodada_liga": 17,
        "time1": "Kyrolina FC",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 14,
        "rodada_liga": 17,
        "time1": "Baguetty e os perus",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 14,
        "rodada_liga": 17,
        "time1": "Ansiedade Prime FC",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 14,
        "rodada_liga": 17,
        "time1": "Arãcanela F.C.",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 14,
        "rodada_liga": 17,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 15,
        "rodada_liga": 18,
        "time1": "GARANTES",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 15,
        "rodada_liga": 18,
        "time1": "Club silencio",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 15,
        "rodada_liga": 18,
        "time1": "Kyrolina FC",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 15,
        "rodada_liga": 18,
        "time1": "Baguetty e os perus",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 15,
        "rodada_liga": 18,
        "time1": "Ansiedade Prime FC",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 15,
        "rodada_liga": 18,
        "time1": "Arãcanela F.C.",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 16,
        "rodada_liga": 19,
        "time1": "Travesseiros confortáveis FC",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 16,
        "rodada_liga": 19,
        "time1": "GARANTES",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 16,
        "rodada_liga": 19,
        "time1": "Club silencio",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 16,
        "rodada_liga": 19,
        "time1": "Kyrolina FC",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 16,
        "rodada_liga": 19,
        "time1": "Baguetty e os perus",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 16,
        "rodada_liga": 19,
        "time1": "Ansiedade Prime FC",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 17,
        "rodada_liga": 20,
        "time1": "São Janumário FC",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 17,
        "rodada_liga": 20,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 17,
        "rodada_liga": 20,
        "time1": "GARANTES",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 17,
        "rodada_liga": 20,
        "time1": "Club silencio",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 17,
        "rodada_liga": 20,
        "time1": "Kyrolina FC",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 17,
        "rodada_liga": 20,
        "time1": "Baguetty e os perus",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 18,
        "rodada_liga": 21,
        "time1": "Paquetetra",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 18,
        "rodada_liga": 21,
        "time1": "São Janumário FC",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 18,
        "rodada_liga": 21,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 18,
        "rodada_liga": 21,
        "time1": "GARANTES",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 18,
        "rodada_liga": 21,
        "time1": "Club silencio",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 18,
        "rodada_liga": 21,
        "time1": "Kyrolina FC",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 19,
        "rodada_liga": 22,
        "time1": "Inhames",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 19,
        "rodada_liga": 22,
        "time1": "Paquetetra",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 19,
        "rodada_liga": 22,
        "time1": "São Janumário FC",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 19,
        "rodada_liga": 22,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 19,
        "rodada_liga": 22,
        "time1": "GARANTES",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 19,
        "rodada_liga": 22,
        "time1": "Club silencio",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 20,
        "rodada_liga": 23,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 20,
        "rodada_liga": 23,
        "time1": "Arãcanela F.C.",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 20,
        "rodada_liga": 23,
        "time1": "Ansiedade Prime FC",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 20,
        "rodada_liga": 23,
        "time1": "Baguetty e os perus",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 20,
        "rodada_liga": 23,
        "time1": "Kyrolina FC",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 20,
        "rodada_liga": 23,
        "time1": "Club silencio",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 21,
        "rodada_liga": 24,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 21,
        "rodada_liga": 24,
        "time1": "Ansiedade Prime FC",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 21,
        "rodada_liga": 24,
        "time1": "Baguetty e os perus",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 21,
        "rodada_liga": 24,
        "time1": "Kyrolina FC",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 21,
        "rodada_liga": 24,
        "time1": "Club silencio",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 21,
        "rodada_liga": 24,
        "time1": "GARANTES",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 22,
        "rodada_liga": 25,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 22,
        "rodada_liga": 25,
        "time1": "Baguetty e os perus",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 22,
        "rodada_liga": 25,
        "time1": "Kyrolina FC",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 22,
        "rodada_liga": 25,
        "time1": "Club silencio",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 22,
        "rodada_liga": 25,
        "time1": "GARANTES",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 22,
        "rodada_liga": 25,
        "time1": "Travesseiros confortáveis FC",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 23,
        "rodada_liga": 26,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 23,
        "rodada_liga": 26,
        "time1": "Kyrolina FC",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 23,
        "rodada_liga": 26,
        "time1": "Club silencio",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 23,
        "rodada_liga": 26,
        "time1": "GARANTES",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 23,
        "rodada_liga": 26,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 23,
        "rodada_liga": 26,
        "time1": "São Janumário FC",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 24,
        "rodada_liga": 27,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 24,
        "rodada_liga": 27,
        "time1": "Club silencio",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 24,
        "rodada_liga": 27,
        "time1": "GARANTES",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 24,
        "rodada_liga": 27,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 24,
        "rodada_liga": 27,
        "time1": "São Janumário FC",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 24,
        "rodada_liga": 27,
        "time1": "Paquetetra",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 25,
        "rodada_liga": 28,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 25,
        "rodada_liga": 28,
        "time1": "GARANTES",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 25,
        "rodada_liga": 28,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 25,
        "rodada_liga": 28,
        "time1": "São Janumário FC",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 25,
        "rodada_liga": 28,
        "time1": "Paquetetra",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 25,
        "rodada_liga": 28,
        "time1": "Inhames",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 26,
        "rodada_liga": 29,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 26,
        "rodada_liga": 29,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 26,
        "rodada_liga": 29,
        "time1": "São Janumário FC",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 26,
        "rodada_liga": 29,
        "time1": "Paquetetra",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 26,
        "rodada_liga": 29,
        "time1": "Inhames",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 26,
        "rodada_liga": 29,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 30,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 30,
        "time1": "São Janumário FC",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 30,
        "time1": "Paquetetra",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 30,
        "time1": "Inhames",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 30,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 30,
        "time1": "Arãcanela F.C.",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 31,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 31,
        "time1": "Paquetetra",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 31,
        "time1": "Inhames",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 31,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 31,
        "time1": "Arãcanela F.C.",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 31,
        "time1": "Ansiedade Prime FC",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 32,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 32,
        "time1": "Inhames",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 32,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 32,
        "time1": "Arãcanela F.C.",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 32,
        "time1": "Ansiedade Prime FC",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 32,
        "time1": "Baguetty e os perus",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 33,
        "time1": "CAIO JÚNIOR F.C. ®️",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 33,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 33,
        "time1": "Arãcanela F.C.",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 33,
        "time1": "Ansiedade Prime FC",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 33,
        "time1": "Baguetty e os perus",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 33,
        "time1": "Kyrolina FC",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 34,
        "time1": "Pigeon Boiteux OSC",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 34,
        "time1": "Inhames",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 34,
        "time1": "Paquetetra",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 34,
        "time1": "São Janumário FC",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 34,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 34,
        "time1": "GARANTES",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 35,
        "time1": "Arãcanela F.C.",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 35,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 35,
        "time1": "Inhames",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 35,
        "time1": "Paquetetra",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 35,
        "time1": "São Janumário FC",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 35,
        "time1": "Travesseiros confortáveis FC",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 30,
        "rodada_liga": 36,
        "time1": "Ansiedade Prime FC",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 30,
        "rodada_liga": 36,
        "time1": "Arãcanela F.C.",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 30,
        "rodada_liga": 36,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 30,
        "rodada_liga": 36,
        "time1": "Inhames",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 30,
        "rodada_liga": 36,
        "time1": "Paquetetra",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 30,
        "rodada_liga": 36,
        "time1": "São Janumário FC",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 31,
        "rodada_liga": 37,
        "time1": "Baguetty e os perus",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 31,
        "rodada_liga": 37,
        "time1": "Ansiedade Prime FC",
        "time2": "Kyrolina FC",
    },
    {
        "rodada_brasileirao": 31,
        "rodada_liga": 37,
        "time1": "Arãcanela F.C.",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 31,
        "rodada_liga": 37,
        "time1": "Pigeon Boiteux OSC",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 31,
        "rodada_liga": 37,
        "time1": "Inhames",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 31,
        "rodada_liga": 37,
        "time1": "Paquetetra",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 32,
        "rodada_liga": 38,
        "time1": "Kyrolina FC",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 32,
        "rodada_liga": 38,
        "time1": "Baguetty e os perus",
        "time2": "Club silencio",
    },
    {
        "rodada_brasileirao": 32,
        "rodada_liga": 38,
        "time1": "Ansiedade Prime FC",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 32,
        "rodada_liga": 38,
        "time1": "Arãcanela F.C.",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 32,
        "rodada_liga": 38,
        "time1": "Pigeon Boiteux OSC",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 32,
        "rodada_liga": 38,
        "time1": "Inhames",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 33,
        "rodada_liga": 39,
        "time1": "Club silencio",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 33,
        "rodada_liga": 39,
        "time1": "Kyrolina FC",
        "time2": "GARANTES",
    },
    {
        "rodada_brasileirao": 33,
        "rodada_liga": 39,
        "time1": "Baguetty e os perus",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 33,
        "rodada_liga": 39,
        "time1": "Ansiedade Prime FC",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 33,
        "rodada_liga": 39,
        "time1": "Arãcanela F.C.",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 33,
        "rodada_liga": 39,
        "time1": "Pigeon Boiteux OSC",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 34,
        "rodada_liga": 40,
        "time1": "GARANTES",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 34,
        "rodada_liga": 40,
        "time1": "Club silencio",
        "time2": "Travesseiros confortáveis FC",
    },
    {
        "rodada_brasileirao": 34,
        "rodada_liga": 40,
        "time1": "Kyrolina FC",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 34,
        "rodada_liga": 40,
        "time1": "Baguetty e os perus",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 34,
        "rodada_liga": 40,
        "time1": "Ansiedade Prime FC",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 34,
        "rodada_liga": 40,
        "time1": "Arãcanela F.C.",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 35,
        "rodada_liga": 41,
        "time1": "Travesseiros confortáveis FC",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 35,
        "rodada_liga": 41,
        "time1": "GARANTES",
        "time2": "São Janumário FC",
    },
    {
        "rodada_brasileirao": 35,
        "rodada_liga": 41,
        "time1": "Club silencio",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 35,
        "rodada_liga": 41,
        "time1": "Kyrolina FC",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 35,
        "rodada_liga": 41,
        "time1": "Baguetty e os perus",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 35,
        "rodada_liga": 41,
        "time1": "Ansiedade Prime FC",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 36,
        "rodada_liga": 42,
        "time1": "São Janumário FC",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 36,
        "rodada_liga": 42,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Paquetetra",
    },
    {
        "rodada_brasileirao": 36,
        "rodada_liga": 42,
        "time1": "GARANTES",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 36,
        "rodada_liga": 42,
        "time1": "Club silencio",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 36,
        "rodada_liga": 42,
        "time1": "Kyrolina FC",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 36,
        "rodada_liga": 42,
        "time1": "Baguetty e os perus",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 37,
        "rodada_liga": 43,
        "time1": "Paquetetra",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 37,
        "rodada_liga": 43,
        "time1": "São Janumário FC",
        "time2": "Inhames",
    },
    {
        "rodada_brasileirao": 37,
        "rodada_liga": 43,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 37,
        "rodada_liga": 43,
        "time1": "GARANTES",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 37,
        "rodada_liga": 43,
        "time1": "Club silencio",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 37,
        "rodada_liga": 43,
        "time1": "Kyrolina FC",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 38,
        "rodada_liga": 44,
        "time1": "Inhames",
        "time2": "CAIO JÚNIOR F.C. ®️",
    },
    {
        "rodada_brasileirao": 38,
        "rodada_liga": 44,
        "time1": "Paquetetra",
        "time2": "Pigeon Boiteux OSC",
    },
    {
        "rodada_brasileirao": 38,
        "rodada_liga": 44,
        "time1": "São Janumário FC",
        "time2": "Arãcanela F.C.",
    },
    {
        "rodada_brasileirao": 38,
        "rodada_liga": 44,
        "time1": "Travesseiros confortáveis FC",
        "time2": "Ansiedade Prime FC",
    },
    {
        "rodada_brasileirao": 38,
        "rodada_liga": 44,
        "time1": "GARANTES",
        "time2": "Baguetty e os perus",
    },
    {
        "rodada_brasileirao": 38,
        "rodada_liga": 44,
        "time1": "Club silencio",
        "time2": "Kyrolina FC",
    },
]
