CONFRONTOS_LIGA = [
    {
        "rodada_brasileirao": 1,
        "rodada_liga": 1,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 1,
        "rodada_liga": 1,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 1,
        "rodada_liga": 1,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 1,
        "rodada_liga": 1,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 1,
        "rodada_liga": 1,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 1,
        "rodada_liga": 1,
        "time1": "Club silencio (Ruy)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 2,
        "rodada_liga": 2,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 2,
        "rodada_liga": 2,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 2,
        "rodada_liga": 2,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 2,
        "rodada_liga": 2,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 2,
        "rodada_liga": 2,
        "time1": "Club silencio (Ruy)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 2,
        "rodada_liga": 2,
        "time1": "GARANTES (Garantes)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 3,
        "rodada_liga": 3,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 3,
        "rodada_liga": 3,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 3,
        "rodada_liga": 3,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 3,
        "rodada_liga": 3,
        "time1": "Club silencio (Ruy)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 3,
        "rodada_liga": 3,
        "time1": "GARANTES (Garantes)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 3,
        "rodada_liga": 3,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 4,
        "rodada_liga": 4,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 4,
        "rodada_liga": 4,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 4,
        "rodada_liga": 4,
        "time1": "Club silencio (Ruy)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 4,
        "rodada_liga": 4,
        "time1": "GARANTES (Garantes)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 4,
        "rodada_liga": 4,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 4,
        "rodada_liga": 4,
        "time1": "São Janumário FC (Mario)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 5,
        "rodada_liga": 5,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 5,
        "rodada_liga": 5,
        "time1": "Club silencio (Ruy)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 5,
        "rodada_liga": 5,
        "time1": "GARANTES (Garantes)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 5,
        "rodada_liga": 5,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 5,
        "rodada_liga": 5,
        "time1": "São Janumário FC (Mario)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 5,
        "rodada_liga": 5,
        "time1": "Paquetetra (Hammes)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 6,
        "rodada_liga": 6,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 6,
        "rodada_liga": 6,
        "time1": "GARANTES (Garantes)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 6,
        "rodada_liga": 6,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 6,
        "rodada_liga": 6,
        "time1": "São Janumário FC (Mario)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 6,
        "rodada_liga": 6,
        "time1": "Paquetetra (Hammes)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 6,
        "rodada_liga": 6,
        "time1": "Inhames (Ian)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 7,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 7,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 7,
        "time1": "São Janumário FC (Mario)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 7,
        "time1": "Paquetetra (Hammes)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 7,
        "time1": "Inhames (Ian)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 7,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 8,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 8,
        "time1": "São Janumário FC (Mario)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 8,
        "time1": "Paquetetra (Hammes)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 8,
        "time1": "Inhames (Ian)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 8,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 7,
        "rodada_liga": 8,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 9,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 9,
        "time1": "Paquetetra (Hammes)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 9,
        "time1": "Inhames (Ian)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 9,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 9,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 9,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 10,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 10,
        "time1": "Inhames (Ian)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 10,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 10,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 10,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 8,
        "rodada_liga": 10,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 11,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 11,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 11,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 11,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 11,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 11,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 12,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 12,
        "time1": "Inhames (Ian)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 12,
        "time1": "Paquetetra (Hammes)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 12,
        "time1": "São Janumário FC (Mario)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 12,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 9,
        "rodada_liga": 12,
        "time1": "GARANTES (Garantes)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 10,
        "rodada_liga": 13,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 10,
        "rodada_liga": 13,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 10,
        "rodada_liga": 13,
        "time1": "Inhames (Ian)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 10,
        "rodada_liga": 13,
        "time1": "Paquetetra (Hammes)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 10,
        "rodada_liga": 13,
        "time1": "São Janumário FC (Mario)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 10,
        "rodada_liga": 13,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 11,
        "rodada_liga": 14,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 11,
        "rodada_liga": 14,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 11,
        "rodada_liga": 14,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 11,
        "rodada_liga": 14,
        "time1": "Inhames (Ian)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 11,
        "rodada_liga": 14,
        "time1": "Paquetetra (Hammes)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 11,
        "rodada_liga": 14,
        "time1": "São Janumário FC (Mario)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 12,
        "rodada_liga": 15,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 12,
        "rodada_liga": 15,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 12,
        "rodada_liga": 15,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 12,
        "rodada_liga": 15,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 12,
        "rodada_liga": 15,
        "time1": "Inhames (Ian)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 12,
        "rodada_liga": 15,
        "time1": "Paquetetra (Hammes)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 13,
        "rodada_liga": 16,
        "time1": "Kyrolina FC (Renata)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 13,
        "rodada_liga": 16,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 13,
        "rodada_liga": 16,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 13,
        "rodada_liga": 16,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 13,
        "rodada_liga": 16,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 13,
        "rodada_liga": 16,
        "time1": "Inhames (Ian)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 14,
        "rodada_liga": 17,
        "time1": "Club silencio (Ruy)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 14,
        "rodada_liga": 17,
        "time1": "Kyrolina FC (Renata)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 14,
        "rodada_liga": 17,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 14,
        "rodada_liga": 17,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 14,
        "rodada_liga": 17,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 14,
        "rodada_liga": 17,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 15,
        "rodada_liga": 18,
        "time1": "GARANTES (Garantes)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 15,
        "rodada_liga": 18,
        "time1": "Club silencio (Ruy)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 15,
        "rodada_liga": 18,
        "time1": "Kyrolina FC (Renata)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 15,
        "rodada_liga": 18,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 15,
        "rodada_liga": 18,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 15,
        "rodada_liga": 18,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 16,
        "rodada_liga": 19,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 16,
        "rodada_liga": 19,
        "time1": "GARANTES (Garantes)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 16,
        "rodada_liga": 19,
        "time1": "Club silencio (Ruy)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 16,
        "rodada_liga": 19,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 16,
        "rodada_liga": 19,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 16,
        "rodada_liga": 19,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 17,
        "rodada_liga": 20,
        "time1": "São Janumário FC (Mario)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 17,
        "rodada_liga": 20,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 17,
        "rodada_liga": 20,
        "time1": "GARANTES (Garantes)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 17,
        "rodada_liga": 20,
        "time1": "Club silencio (Ruy)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 17,
        "rodada_liga": 20,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 17,
        "rodada_liga": 20,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 18,
        "rodada_liga": 21,
        "time1": "Paquetetra (Hammes)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 18,
        "rodada_liga": 21,
        "time1": "São Janumário FC (Mario)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 18,
        "rodada_liga": 21,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 18,
        "rodada_liga": 21,
        "time1": "GARANTES (Garantes)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 18,
        "rodada_liga": 21,
        "time1": "Club silencio (Ruy)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 18,
        "rodada_liga": 21,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 19,
        "rodada_liga": 22,
        "time1": "Inhames (Ian)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 19,
        "rodada_liga": 22,
        "time1": "Paquetetra (Hammes)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 19,
        "rodada_liga": 22,
        "time1": "São Janumário FC (Mario)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 19,
        "rodada_liga": 22,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 19,
        "rodada_liga": 22,
        "time1": "GARANTES (Garantes)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 19,
        "rodada_liga": 22,
        "time1": "Club silencio (Ruy)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 20,
        "rodada_liga": 23,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 20,
        "rodada_liga": 23,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 20,
        "rodada_liga": 23,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 20,
        "rodada_liga": 23,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 20,
        "rodada_liga": 23,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 20,
        "rodada_liga": 23,
        "time1": "Club silencio (Ruy)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 21,
        "rodada_liga": 24,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 21,
        "rodada_liga": 24,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 21,
        "rodada_liga": 24,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 21,
        "rodada_liga": 24,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 21,
        "rodada_liga": 24,
        "time1": "Club silencio (Ruy)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 21,
        "rodada_liga": 24,
        "time1": "GARANTES (Garantes)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 22,
        "rodada_liga": 25,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 22,
        "rodada_liga": 25,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 22,
        "rodada_liga": 25,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 22,
        "rodada_liga": 25,
        "time1": "Club silencio (Ruy)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 22,
        "rodada_liga": 25,
        "time1": "GARANTES (Garantes)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 22,
        "rodada_liga": 25,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 23,
        "rodada_liga": 26,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 23,
        "rodada_liga": 26,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 23,
        "rodada_liga": 26,
        "time1": "Club silencio (Ruy)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 23,
        "rodada_liga": 26,
        "time1": "GARANTES (Garantes)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 23,
        "rodada_liga": 26,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 23,
        "rodada_liga": 26,
        "time1": "São Janumário FC (Mario)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 24,
        "rodada_liga": 27,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 24,
        "rodada_liga": 27,
        "time1": "Club silencio (Ruy)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 24,
        "rodada_liga": 27,
        "time1": "GARANTES (Garantes)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 24,
        "rodada_liga": 27,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 24,
        "rodada_liga": 27,
        "time1": "São Janumário FC (Mario)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 24,
        "rodada_liga": 27,
        "time1": "Paquetetra (Hammes)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 25,
        "rodada_liga": 28,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 25,
        "rodada_liga": 28,
        "time1": "GARANTES (Garantes)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 25,
        "rodada_liga": 28,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 25,
        "rodada_liga": 28,
        "time1": "São Janumário FC (Mario)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 25,
        "rodada_liga": 28,
        "time1": "Paquetetra (Hammes)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 25,
        "rodada_liga": 28,
        "time1": "Inhames (Ian)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 26,
        "rodada_liga": 29,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 26,
        "rodada_liga": 29,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 26,
        "rodada_liga": 29,
        "time1": "São Janumário FC (Mario)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 26,
        "rodada_liga": 29,
        "time1": "Paquetetra (Hammes)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 26,
        "rodada_liga": 29,
        "time1": "Inhames (Ian)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 26,
        "rodada_liga": 29,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 30,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 30,
        "time1": "São Janumário FC (Mario)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 30,
        "time1": "Paquetetra (Hammes)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 30,
        "time1": "Inhames (Ian)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 30,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 30,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 31,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 31,
        "time1": "Paquetetra (Hammes)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 31,
        "time1": "Inhames (Ian)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 31,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 31,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 27,
        "rodada_liga": 31,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 32,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 32,
        "time1": "Inhames (Ian)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 32,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 32,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 32,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 32,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 33,
        "time1": "CAIO JÚNIOR F.C. ®️ (Rafa)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 33,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 33,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 33,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 33,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 28,
        "rodada_liga": 33,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 34,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 34,
        "time1": "Inhames (Ian)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 34,
        "time1": "Paquetetra (Hammes)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 34,
        "time1": "São Janumário FC (Mario)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 34,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 34,
        "time1": "GARANTES (Garantes)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 35,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 35,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 35,
        "time1": "Inhames (Ian)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 35,
        "time1": "Paquetetra (Hammes)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 35,
        "time1": "São Janumário FC (Mario)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 29,
        "rodada_liga": 35,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 30,
        "rodada_liga": 36,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 30,
        "rodada_liga": 36,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 30,
        "rodada_liga": 36,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 30,
        "rodada_liga": 36,
        "time1": "Inhames (Ian)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 30,
        "rodada_liga": 36,
        "time1": "Paquetetra (Hammes)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 30,
        "rodada_liga": 36,
        "time1": "São Janumário FC (Mario)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 31,
        "rodada_liga": 37,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 31,
        "rodada_liga": 37,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Kyrolina FC (Renata)",
    },
    {
        "rodada_brasileirao": 31,
        "rodada_liga": 37,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 31,
        "rodada_liga": 37,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 31,
        "rodada_liga": 37,
        "time1": "Inhames (Ian)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 31,
        "rodada_liga": 37,
        "time1": "Paquetetra (Hammes)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 32,
        "rodada_liga": 38,
        "time1": "Kyrolina FC (Renata)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 32,
        "rodada_liga": 38,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Club silencio (Ruy)",
    },
    {
        "rodada_brasileirao": 32,
        "rodada_liga": 38,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 32,
        "rodada_liga": 38,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 32,
        "rodada_liga": 38,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 32,
        "rodada_liga": 38,
        "time1": "Inhames (Ian)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 33,
        "rodada_liga": 39,
        "time1": "Club silencio (Ruy)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 33,
        "rodada_liga": 39,
        "time1": "Kyrolina FC (Renata)",
        "time2": "GARANTES (Garantes)",
    },
    {
        "rodada_brasileirao": 33,
        "rodada_liga": 39,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 33,
        "rodada_liga": 39,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 33,
        "rodada_liga": 39,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 33,
        "rodada_liga": 39,
        "time1": "Pigeon Boiteux OSC (PV)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 34,
        "rodada_liga": 40,
        "time1": "GARANTES (Garantes)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 34,
        "rodada_liga": 40,
        "time1": "Club silencio (Ruy)",
        "time2": "Travesseiros confortáveis FC (Bruna)",
    },
    {
        "rodada_brasileirao": 34,
        "rodada_liga": 40,
        "time1": "Kyrolina FC (Renata)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 34,
        "rodada_liga": 40,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 34,
        "rodada_liga": 40,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 34,
        "rodada_liga": 40,
        "time1": "Arãcanela F.C. (Feijó)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 35,
        "rodada_liga": 41,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 35,
        "rodada_liga": 41,
        "time1": "GARANTES (Garantes)",
        "time2": "São Janumário FC (Mario)",
    },
    {
        "rodada_brasileirao": 35,
        "rodada_liga": 41,
        "time1": "Club silencio (Ruy)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 35,
        "rodada_liga": 41,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 35,
        "rodada_liga": 41,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 35,
        "rodada_liga": 41,
        "time1": "Ansiedade Prime FC (Gui)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 36,
        "rodada_liga": 42,
        "time1": "São Janumário FC (Mario)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 36,
        "rodada_liga": 42,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Paquetetra (Hammes)",
    },
    {
        "rodada_brasileirao": 36,
        "rodada_liga": 42,
        "time1": "GARANTES (Garantes)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 36,
        "rodada_liga": 42,
        "time1": "Club silencio (Ruy)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 36,
        "rodada_liga": 42,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 36,
        "rodada_liga": 42,
        "time1": "Baguetty e os perus (Camilla)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 37,
        "rodada_liga": 43,
        "time1": "Paquetetra (Hammes)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 37,
        "rodada_liga": 43,
        "time1": "São Janumário FC (Mario)",
        "time2": "Inhames (Ian)",
    },
    {
        "rodada_brasileirao": 37,
        "rodada_liga": 43,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 37,
        "rodada_liga": 43,
        "time1": "GARANTES (Garantes)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 37,
        "rodada_liga": 43,
        "time1": "Club silencio (Ruy)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 37,
        "rodada_liga": 43,
        "time1": "Kyrolina FC (Renata)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 38,
        "rodada_liga": 44,
        "time1": "Inhames (Ian)",
        "time2": "CAIO JÚNIOR F.C. ®️ (Rafa)",
    },
    {
        "rodada_brasileirao": 38,
        "rodada_liga": 44,
        "time1": "Paquetetra (Hammes)",
        "time2": "Pigeon Boiteux OSC (PV)",
    },
    {
        "rodada_brasileirao": 38,
        "rodada_liga": 44,
        "time1": "São Janumário FC (Mario)",
        "time2": "Arãcanela F.C. (Feijó)",
    },
    {
        "rodada_brasileirao": 38,
        "rodada_liga": 44,
        "time1": "Travesseiros confortáveis FC (Bruna)",
        "time2": "Ansiedade Prime FC (Gui)",
    },
    {
        "rodada_brasileirao": 38,
        "rodada_liga": 44,
        "time1": "GARANTES (Garantes)",
        "time2": "Baguetty e os perus (Camilla)",
    },
    {
        "rodada_brasileirao": 38,
        "rodada_liga": 44,
        "time1": "Club silencio (Ruy)",
        "time2": "Kyrolina FC (Renata)",
    },
]
